/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'report-export-files': ReportExportFile;
    categories: Category;
    products: Product;
    'product-imports': ProductImport;
    reservations: Reservation;
    leads: Lead;
    customers: Customer;
    'client-interests': ClientInterest;
    opportunities: Opportunity;
    sales: Sale;
    'after-sales': AfterSale;
    tasks: Task;
    shipments: Shipment;
    occurrences: Occurrence;
    activities: Activity;
    'report-exports': ReportExport;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'report-export-files': ReportExportFilesSelect<false> | ReportExportFilesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-imports': ProductImportsSelect<false> | ProductImportsSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'client-interests': ClientInterestsSelect<false> | ClientInterestsSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    sales: SalesSelect<false> | SalesSelect<true>;
    'after-sales': AfterSalesSelect<false> | AfterSalesSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    shipments: ShipmentsSelect<false> | ShipmentsSelect<true>;
    occurrences: OccurrencesSelect<false> | OccurrencesSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'report-exports': ReportExportsSelect<false> | ReportExportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    about: About;
    contact: Contact;
    'collection-page': CollectionPage;
    navigation: Navigation;
    'site-settings': SiteSetting;
    'after-sales-automation': AfterSalesAutomation;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    'collection-page': CollectionPageSelect<false> | CollectionPageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'after-sales-automation': AfterSalesAutomationSelect<false> | AfterSalesAutomationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createAfterSalesTask: TaskCreateAfterSalesTask;
      syncActiveShipments: TaskSyncActiveShipments;
      generateReportExport: TaskGenerateReportExport;
      productImport: TaskProductImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Controla o acesso às áreas editorial e comercial.
   */
  role: 'admin' | 'editor' | 'commercial';
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Obrigatório para imagens informativas e acessibilidade.
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  sourceSha256?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    productCard?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-export-files".
 */
export interface ReportExportFile {
  id: number;
  semanticVersion: string;
  generatedAt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  /**
   * Status controla participação no catálogo. Publicação é controlada separadamente pelo workflow do Payload.
   */
  status: 'active' | 'archive';
  nodeType?: ('collection' | 'editorial' | 'external' | 'group') | null;
  taxonomyAxis?: ('navigation' | 'piece_type' | 'collection' | 'environment' | 'campaign' | 'service') | null;
  /**
   * A hierarquia é validada no servidor; relações cíclicas são rejeitadas.
   */
  parent?: (number | null) | Category;
  description?: string | null;
  order?: number | null;
  menu?: {
    showInMenu?: boolean | null;
    label?: string | null;
    visibility?: ('all' | 'desktop' | 'mobile') | null;
    icon?: string | null;
  };
  listingMode?: ('assigned' | 'descendants' | 'rules' | 'hybrid') | null;
  listingRules?: {
    availability?: ('unique' | 'available' | 'made_to_order' | 'limited')[] | null;
    materials?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    productStatus?: ('active' | 'archived')[] | null;
    minPrice?: number | null;
    maxPrice?: number | null;
    publishedAfter?: string | null;
    publishedBefore?: string | null;
    sort?: ('editorial' | 'newest' | 'price_asc' | 'price_desc' | 'name_asc') | null;
  };
  collectionPage?: {
    eyebrow?: string | null;
    shortDescription?: string | null;
    visibleFilters?:
      ('category' | 'collection' | 'environment' | 'piece_type' | 'material' | 'availability' | 'price')[] | null;
    defaultSort?: ('editorial' | 'newest' | 'price_asc' | 'price_desc' | 'name_asc') | null;
    productsPerPage?: number | null;
    showProductCount?: boolean | null;
    layout?: ('grid' | 'editorial') | null;
  };
  externalURL?: string | null;
  hubPath?: string | null;
  image?: (number | null) | Media;
  searchTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  contentBlocks?:
    | (
        | {
            placement: 'before' | 'after';
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            placement: 'before' | 'after';
            image: number | Media;
            alt: string;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            placement: 'before' | 'after';
            eyebrow?: string | null;
            title: string;
            copy: string;
            image: number | Media;
            imagePosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageText';
          }
        | {
            placement: 'before' | 'after';
            eyebrow?: string | null;
            title: string;
            copy: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'manifesto';
          }
        | {
            placement: 'before' | 'after';
            material: string;
            title: string;
            copy?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'materialHighlight';
          }
        | {
            placement: 'before' | 'after';
            title?: string | null;
            copy?: string | null;
            label: string;
            destination?: (number | null) | Category;
            externalURL?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            placement: 'before' | 'after';
            items: {
              image: number | Media;
              alt: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            placement: 'before' | 'after';
            label?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  menuHighlights?:
    | {
        title?: string | null;
        eyebrow?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        linkLabel?: string | null;
        destination?: (number | null) | Category;
        externalURL?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    socialImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  publicationRevision?: string | null;
  publicationContractVersion?: string | null;
  titleNormalized?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  subtitle?: string | null;
  slug: string;
  /**
   * Gerado automaticamente (ex.: OBJ-AB12CD34).
   */
  code: string;
  /**
   * Rascunho/publicação é controlado separadamente pelo workflow do Payload.
   */
  catalogStatus: 'active' | 'archived';
  /**
   * O produto pode aparecer em mais de uma prateleira. Agrupadores de menu não são selecionáveis.
   */
  categories?: (number | Category)[] | null;
  material?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Exemplo: peça única, edição de 8 ou numerada.
   */
  edition?: string | null;
  attributes?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A imagem marcada como Capa é a principal.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Exemplo: verde-frente. Usada por variantes.
         */
        mediaKey?: string | null;
        role?: ('cover' | 'detail' | 'context' | 'scale') | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Para peça única, defina Edição = "Peça única" e Disponibilidade = "Disponível".
   */
  availability: 'unique' | 'available' | 'made_to_order' | 'limited';
  /**
   * Dados físicos estruturados. Usados no card, em frete e em relatórios. Deixe em branco o que não se aplica.
   */
  physicalSpecs?: {
    /**
     * Ex.: 180 = 18 cm.
     */
    heightMm?: number | null;
    widthMm?: number | null;
    depthMm?: number | null;
    /**
     * Ex.: 1200 = 1,2 kg.
     */
    weightGrams?: number | null;
  };
  priceMode: 'fixed' | 'inquiry';
  /**
   * Exemplo: R$ 14.900,00 = 1490000.
   */
  basePriceCents?: number | null;
  /**
   * Cadastre Tamanho, Cor, Kit e seus valores antes das combinações.
   */
  optionDefinitions?:
    | {
        code: string;
        label: string;
        values: {
          value: string;
          label: string;
          swatch?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        sku: string;
        selection?:
          | {
              option: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        priceMode: 'inherit' | 'fixed' | 'inquiry';
        priceCents?: number | null;
        status: 'enabled' | 'disabled';
        mediaKeys?:
          | {
              key: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  searchTerms?:
    | {
        term: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    socialImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  publicationRevision?: string | null;
  publicationContractVersion?: string | null;
  publicationReady?: boolean | null;
  publicationIssues?:
    | {
        message: string;
        id?: string | null;
      }[]
    | null;
  codeNormalized?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-imports".
 */
export interface ProductImport {
  id: number;
  status: 'queued' | 'processing' | 'completed' | 'completed_with_errors' | 'failed' | 'cancelled';
  idempotencyKey: string;
  requestedBy?: (number | null) | User;
  requestedByName?: string | null;
  requestedByEmail?: string | null;
  requestedAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  totalRows: number;
  processedRows: number;
  created: number;
  updated: number;
  skipped: number;
  errored: number;
  payloadSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  results?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  productId: number;
  productSlug: string;
  variantSku?: string | null;
  /**
   * Peça única: no máximo uma reserva ativa.
   */
  uniquePiece?: boolean | null;
  status: 'held' | 'confirmed' | 'released' | 'expired';
  idempotencyKey: string;
  reservedUntil?: string | null;
  priceCents?: number | null;
  /**
   * Referência do comprador (sessão/e-mail).
   */
  buyerRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Leads representam exclusivamente aquisição e qualificação. Negociação, etapa, próxima ação e fechamento pertencem a Opportunities.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone?: string | null;
  email?: string | null;
  source: 'instagram' | 'referral' | 'site' | 'architect' | 'organic' | 'whatsapp' | 'other';
  owner?: (number | null) | User;
  interestCategories?: (number | Category)[] | null;
  interestedProducts?: (number | Product)[] | null;
  notes?: string | null;
  customer?: (number | null) | Customer;
  opportunity?: (number | null) | Opportunity;
  opportunityMigratedAt?: string | null;
  marketingConsent?: boolean | null;
  consentRecordedAt?: string | null;
  stage?: ('new' | 'curation' | 'proposal' | 'negotiation' | 'won' | 'lost') | null;
  nextAction?: string | null;
  nextActionAt?: string | null;
  closedAt?: string | null;
  lossReason?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  company?: string | null;
  phone?: string | null;
  email?: string | null;
  city?: string | null;
  state?: string | null;
  normalizedPhone?: string | null;
  normalizedEmail?: string | null;
  status?: ('active' | 'follow_up' | 'inactive' | 'archived') | null;
  origin?: ('instagram' | 'referral' | 'site' | 'architect' | 'organic' | 'whatsapp' | 'other') | null;
  owner?: (number | null) | User;
  sourceLead?: (number | null) | Lead;
  interestProfile?: {
    categories?: (number | Category)[] | null;
    materials?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    investmentMinCents?: number | null;
    investmentMaxCents?: number | null;
  };
  preferences?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  relationshipNotes?: string | null;
  mergedInto?: (number | null) | Customer;
  mergedAt?: string | null;
  marketingConsent?: boolean | null;
  consentRecordedAt?: string | null;
  consentWithdrawnAt?: string | null;
  privacyRequestStatus?: ('none' | 'requested' | 'reviewing' | 'blocked' | 'completed') | null;
  privacyRequestAt?: string | null;
  privacyRequestCompletedAt?: string | null;
  retentionReviewAt?: string | null;
  processingRestricted?: boolean | null;
  dataHandlingNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  /**
   * Gerado automaticamente pelo domínio comercial.
   */
  code: string;
  /**
   * Pode permanecer vazio durante qualificação; torna-se obrigatório ao ganhar.
   */
  customer?: (number | null) | Customer;
  source: 'instagram' | 'referral' | 'site' | 'architect' | 'organic' | 'whatsapp' | 'other';
  stage: 'new' | 'curation' | 'proposal' | 'negotiation' | 'won' | 'lost';
  /**
   * Usado para ordenar cards no Pipeline.
   */
  rank: number;
  owner?: (number | null) | User;
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  interestedProducts?: (number | Product)[] | null;
  /**
   * Valor informado pelo operador. Nunca é estimado automaticamente.
   */
  estimatedValueCents?: number | null;
  nextAction?: string | null;
  nextActionAt?: string | null;
  expectedCloseAt?: string | null;
  closedAt?: string | null;
  lossReason?:
    ('price' | 'budget' | 'timing' | 'no_response' | 'product_fit' | 'competitor' | 'changed_mind' | 'other') | null;
  lossNotes?: string | null;
  wonSale?: (number | null) | Sale;
  /**
   * Vínculo mantido durante o ciclo de compatibilidade.
   */
  sourceLead?: (number | null) | Lead;
  migrationVersion?: string | null;
  migratedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sale representa a transação ganha e seu fulfillment. Negociação comercial pertence a Opportunities.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales".
 */
export interface Sale {
  id: number;
  number: string;
  customer: number | Customer;
  /**
   * Preenchida pelo workflow de ganho ou vinculada explicitamente em vendas legadas.
   */
  opportunity?: (number | null) | Opportunity;
  channel: 'whatsapp' | 'instagram' | 'site' | 'referral' | 'architect' | 'other';
  status: 'draft' | 'proposal' | 'negotiation' | 'confirmed' | 'production' | 'ready' | 'delivered' | 'cancelled';
  owner?: (number | null) | User;
  confirmedAt?: string | null;
  nextAction?: string | null;
  nextActionAt?: string | null;
  items: {
    product: number | Product;
    variantSku?: string | null;
    /**
     * Preenchido automaticamente a partir do produto.
     */
    snapshotTitle: string;
    snapshotSlug: string;
    snapshotSku?: string | null;
    snapshotSelection?: string | null;
    priceMode: 'fixed' | 'inquiry';
    /**
     * Automático para preço fixo. Em itens sob consulta, informe apenas após o valor ser negociado.
     */
    unitPriceCents?: number | null;
    quantity: number;
    id?: string | null;
  }[];
  discountCents?: number | null;
  shippingCents?: number | null;
  subtotalCents?: number | null;
  /**
   * Calculado automaticamente a partir dos itens, desconto e frete.
   */
  totalCents?: number | null;
  expectedDeliveryAt?: string | null;
  deliveredAt?: string | null;
  deliveryMode?: ('carrier' | 'pickup' | 'own_delivery') | null;
  deliveryNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-interests".
 */
export interface ClientInterest {
  id: number;
  customer: number | Customer;
  product: number | Product;
  status: 'active' | 'curation' | 'purchased' | 'paused' | 'archived';
  source: 'manual' | 'lead' | 'sale' | 'after_sale';
  owner?: (number | null) | User;
  notes?: string | null;
  addedAt: string;
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "after-sales".
 */
export interface AfterSale {
  id: number;
  caseNumber?: string | null;
  sale: number | Sale;
  customer: number | Customer;
  summary?: string | null;
  status: 'open' | 'following' | 'resolved' | 'closed';
  priority: 'low' | 'normal' | 'high' | 'urgent';
  owner?: (number | null) | User;
  openedAt?: string | null;
  closedAt?: string | null;
  expectedDeliveryAt?: string | null;
  deliveredAt?: string | null;
  deliveryNotes?: string | null;
  /**
   * Novos follow-ups devem ser criados em Tasks. Este array permanece somente durante o ciclo de migração.
   */
  followUps?:
    | {
        moment: 'd3' | 'd15' | 'd90' | 'custom';
        dueAt: string;
        purpose: 'receipt' | 'satisfaction' | 'testimonial' | 'maintenance' | 'curation' | 'other';
        status: 'pending' | 'done' | 'cancelled';
        notes?: string | null;
        completedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  incidentType?: ('none' | 'damage' | 'adjustment' | 'maintenance' | 'other') | null;
  incidentDetails?: string | null;
  resolution?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  title: string;
  type?: ('delivery_confirmation' | 'satisfaction' | 'testimonial' | 'maintenance' | 'curation' | 'custom') | null;
  status: 'pending' | 'in_progress' | 'done' | 'cancelled';
  priority: 'low' | 'normal' | 'high' | 'urgent';
  dueAt: string;
  assignee?: (number | null) | User;
  relatedTo?:
    | (
        | {
            relationTo: 'leads';
            value: number | Lead;
          }
        | {
            relationTo: 'customers';
            value: number | Customer;
          }
        | {
            relationTo: 'opportunities';
            value: number | Opportunity;
          }
        | {
            relationTo: 'sales';
            value: number | Sale;
          }
        | {
            relationTo: 'after-sales';
            value: number | AfterSale;
          }
        | {
            relationTo: 'shipments';
            value: number | Shipment;
          }
        | {
            relationTo: 'occurrences';
            value: number | Occurrence;
          }
      )[]
    | null;
  notes?: string | null;
  completedAt?: string | null;
  /**
   * Garante idempotência para Tasks criadas pela Payload Jobs Queue.
   */
  automationKey?: string | null;
  legacySourceKey?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments".
 */
export interface Shipment {
  id: number;
  afterSalesCase: number | AfterSale;
  sale: number | Sale;
  customer: number | Customer;
  carrier?: string | null;
  trackingCode?: string | null;
  status: 'confirmed' | 'collected' | 'in_transit' | 'out_for_delivery' | 'delivered' | 'exception' | 'cancelled';
  estimatedDelivery?: string | null;
  deliveredAt?: string | null;
  lastEvent?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occurrences".
 */
export interface Occurrence {
  id: number;
  afterSalesCase: number | AfterSale;
  sale: number | Sale;
  customer: number | Customer;
  type: 'damage' | 'adjustment' | 'maintenance' | 'delivery_delay' | 'return' | 'other';
  severity: 'low' | 'medium' | 'high' | 'critical';
  status: 'open' | 'investigating' | 'waiting_customer' | 'resolved' | 'closed';
  owner?: (number | null) | User;
  description: string;
  resolution?: string | null;
  openedAt: string;
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  eventType?:
    | (
        | 'opportunity.created'
        | 'opportunity.migrated'
        | 'sale.created'
        | 'opportunity.stage_changed'
        | 'interest.added'
        | 'task.created'
        | 'task.status_changed'
        | 'followup.completed'
        | 'shipment.status_changed'
        | 'shipment.delivered'
        | 'occurrence.opened'
        | 'occurrence.status_changed'
        | 'occurrence.resolved'
        | 'note.created'
        | 'contact.logged'
      )
    | null;
  /**
   * Derivado automaticamente do evento estruturado.
   */
  kind: 'contact' | 'message' | 'proposal' | 'stage_change' | 'sale' | 'note' | 'delivery' | 'follow_up' | 'occurrence';
  occurredAt: string;
  summary: string;
  details?: string | null;
  owner?: (number | null) | User;
  opportunity?: (number | null) | Opportunity;
  fromStage?: ('new' | 'curation' | 'proposal' | 'negotiation' | 'won' | 'lost') | null;
  toStage?: ('new' | 'curation' | 'proposal' | 'negotiation' | 'won' | 'lost') | null;
  lossReason?:
    ('price' | 'budget' | 'timing' | 'no_response' | 'product_fit' | 'competitor' | 'changed_mind' | 'other') | null;
  relatedTo: (
    | {
        relationTo: 'leads';
        value: number | Lead;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'opportunities';
        value: number | Opportunity;
      }
    | {
        relationTo: 'sales';
        value: number | Sale;
      }
    | {
        relationTo: 'after-sales';
        value: number | AfterSale;
      }
    | {
        relationTo: 'tasks';
        value: number | Task;
      }
    | {
        relationTo: 'shipments';
        value: number | Shipment;
      }
    | {
        relationTo: 'occurrences';
        value: number | Occurrence;
      }
    | {
        relationTo: 'client-interests';
        value: number | ClientInterest;
      }
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-exports".
 */
export interface ReportExport {
  id: number;
  status: 'queued' | 'processing' | 'ready' | 'failed';
  delivery: 'sync' | 'job';
  requestedAt: string;
  startedAt?: string | null;
  completedAt?: string | null;
  requestedBy: number | User;
  requestedByName: string;
  requestedByEmail?: string | null;
  filename: string;
  semanticVersion: string;
  snapshotGeneratedAt?: string | null;
  filters:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  estimatedRows?: number | null;
  fileSizeBytes?: number | null;
  file?: (number | null) | ReportExportFile;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createAfterSalesTask' | 'syncActiveShipments' | 'generateReportExport' | 'productImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    ('inline' | 'createAfterSalesTask' | 'syncActiveShipments' | 'generateReportExport' | 'productImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'report-export-files';
        value: number | ReportExportFile;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-imports';
        value: number | ProductImport;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'client-interests';
        value: number | ClientInterest;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'sales';
        value: number | Sale;
      } | null)
    | ({
        relationTo: 'after-sales';
        value: number | AfterSale;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'shipments';
        value: number | Shipment;
      } | null)
    | ({
        relationTo: 'occurrences';
        value: number | Occurrence;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'report-exports';
        value: number | ReportExport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  sourceSha256?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        productCard?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-export-files_select".
 */
export interface ReportExportFilesSelect<T extends boolean = true> {
  semanticVersion?: T;
  generatedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  nodeType?: T;
  taxonomyAxis?: T;
  parent?: T;
  description?: T;
  order?: T;
  menu?:
    | T
    | {
        showInMenu?: T;
        label?: T;
        visibility?: T;
        icon?: T;
      };
  listingMode?: T;
  listingRules?:
    | T
    | {
        availability?: T;
        materials?:
          | T
          | {
              value?: T;
              id?: T;
            };
        productStatus?: T;
        minPrice?: T;
        maxPrice?: T;
        publishedAfter?: T;
        publishedBefore?: T;
        sort?: T;
      };
  collectionPage?:
    | T
    | {
        eyebrow?: T;
        shortDescription?: T;
        visibleFilters?: T;
        defaultSort?: T;
        productsPerPage?: T;
        showProductCount?: T;
        layout?: T;
      };
  externalURL?: T;
  hubPath?: T;
  image?: T;
  searchTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  contentBlocks?:
    | T
    | {
        richText?:
          | T
          | {
              placement?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              placement?: T;
              image?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              placement?: T;
              eyebrow?: T;
              title?: T;
              copy?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        manifesto?:
          | T
          | {
              placement?: T;
              eyebrow?: T;
              title?: T;
              copy?: T;
              id?: T;
              blockName?: T;
            };
        materialHighlight?:
          | T
          | {
              placement?: T;
              material?: T;
              title?: T;
              copy?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              placement?: T;
              title?: T;
              copy?: T;
              label?: T;
              destination?: T;
              externalURL?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              placement?: T;
              items?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              placement?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  menuHighlights?:
    | T
    | {
        title?: T;
        eyebrow?: T;
        description?: T;
        image?: T;
        linkLabel?: T;
        destination?: T;
        externalURL?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  publicationRevision?: T;
  publicationContractVersion?: T;
  titleNormalized?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  slug?: T;
  code?: T;
  catalogStatus?: T;
  categories?: T;
  material?: T;
  description?: T;
  edition?: T;
  attributes?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        mediaKey?: T;
        role?: T;
        alt?: T;
        id?: T;
      };
  availability?: T;
  physicalSpecs?:
    | T
    | {
        heightMm?: T;
        widthMm?: T;
        depthMm?: T;
        weightGrams?: T;
      };
  priceMode?: T;
  basePriceCents?: T;
  optionDefinitions?:
    | T
    | {
        code?: T;
        label?: T;
        values?:
          | T
          | {
              value?: T;
              label?: T;
              swatch?: T;
              id?: T;
            };
        id?: T;
      };
  variants?:
    | T
    | {
        sku?: T;
        selection?:
          | T
          | {
              option?: T;
              value?: T;
              id?: T;
            };
        priceMode?: T;
        priceCents?: T;
        status?: T;
        mediaKeys?:
          | T
          | {
              key?: T;
              id?: T;
            };
        id?: T;
      };
  searchTerms?:
    | T
    | {
        term?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  publicationRevision?: T;
  publicationContractVersion?: T;
  publicationReady?: T;
  publicationIssues?:
    | T
    | {
        message?: T;
        id?: T;
      };
  codeNormalized?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-imports_select".
 */
export interface ProductImportsSelect<T extends boolean = true> {
  status?: T;
  idempotencyKey?: T;
  requestedBy?: T;
  requestedByName?: T;
  requestedByEmail?: T;
  requestedAt?: T;
  startedAt?: T;
  completedAt?: T;
  totalRows?: T;
  processedRows?: T;
  created?: T;
  updated?: T;
  skipped?: T;
  errored?: T;
  payloadSnapshot?: T;
  results?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  productId?: T;
  productSlug?: T;
  variantSku?: T;
  uniquePiece?: T;
  status?: T;
  idempotencyKey?: T;
  reservedUntil?: T;
  priceCents?: T;
  buyerRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  source?: T;
  owner?: T;
  interestCategories?: T;
  interestedProducts?: T;
  notes?: T;
  customer?: T;
  opportunity?: T;
  opportunityMigratedAt?: T;
  marketingConsent?: T;
  consentRecordedAt?: T;
  stage?: T;
  nextAction?: T;
  nextActionAt?: T;
  closedAt?: T;
  lossReason?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  phone?: T;
  email?: T;
  city?: T;
  state?: T;
  normalizedPhone?: T;
  normalizedEmail?: T;
  status?: T;
  origin?: T;
  owner?: T;
  sourceLead?: T;
  interestProfile?:
    | T
    | {
        categories?: T;
        materials?:
          | T
          | {
              value?: T;
              id?: T;
            };
        investmentMinCents?: T;
        investmentMaxCents?: T;
      };
  preferences?:
    | T
    | {
        value?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  relationshipNotes?: T;
  mergedInto?: T;
  mergedAt?: T;
  marketingConsent?: T;
  consentRecordedAt?: T;
  consentWithdrawnAt?: T;
  privacyRequestStatus?: T;
  privacyRequestAt?: T;
  privacyRequestCompletedAt?: T;
  retentionReviewAt?: T;
  processingRestricted?: T;
  dataHandlingNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-interests_select".
 */
export interface ClientInterestsSelect<T extends boolean = true> {
  customer?: T;
  product?: T;
  status?: T;
  source?: T;
  owner?: T;
  notes?: T;
  addedAt?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  code?: T;
  customer?: T;
  source?: T;
  stage?: T;
  rank?: T;
  owner?: T;
  priority?: T;
  interestedProducts?: T;
  estimatedValueCents?: T;
  nextAction?: T;
  nextActionAt?: T;
  expectedCloseAt?: T;
  closedAt?: T;
  lossReason?: T;
  lossNotes?: T;
  wonSale?: T;
  sourceLead?: T;
  migrationVersion?: T;
  migratedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales_select".
 */
export interface SalesSelect<T extends boolean = true> {
  number?: T;
  customer?: T;
  opportunity?: T;
  channel?: T;
  status?: T;
  owner?: T;
  confirmedAt?: T;
  nextAction?: T;
  nextActionAt?: T;
  items?:
    | T
    | {
        product?: T;
        variantSku?: T;
        snapshotTitle?: T;
        snapshotSlug?: T;
        snapshotSku?: T;
        snapshotSelection?: T;
        priceMode?: T;
        unitPriceCents?: T;
        quantity?: T;
        id?: T;
      };
  discountCents?: T;
  shippingCents?: T;
  subtotalCents?: T;
  totalCents?: T;
  expectedDeliveryAt?: T;
  deliveredAt?: T;
  deliveryMode?: T;
  deliveryNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "after-sales_select".
 */
export interface AfterSalesSelect<T extends boolean = true> {
  caseNumber?: T;
  sale?: T;
  customer?: T;
  summary?: T;
  status?: T;
  priority?: T;
  owner?: T;
  openedAt?: T;
  closedAt?: T;
  expectedDeliveryAt?: T;
  deliveredAt?: T;
  deliveryNotes?: T;
  followUps?:
    | T
    | {
        moment?: T;
        dueAt?: T;
        purpose?: T;
        status?: T;
        notes?: T;
        completedAt?: T;
        id?: T;
      };
  incidentType?: T;
  incidentDetails?: T;
  resolution?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  status?: T;
  priority?: T;
  dueAt?: T;
  assignee?: T;
  relatedTo?: T;
  notes?: T;
  completedAt?: T;
  automationKey?: T;
  legacySourceKey?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments_select".
 */
export interface ShipmentsSelect<T extends boolean = true> {
  afterSalesCase?: T;
  sale?: T;
  customer?: T;
  carrier?: T;
  trackingCode?: T;
  status?: T;
  estimatedDelivery?: T;
  deliveredAt?: T;
  lastEvent?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occurrences_select".
 */
export interface OccurrencesSelect<T extends boolean = true> {
  afterSalesCase?: T;
  sale?: T;
  customer?: T;
  type?: T;
  severity?: T;
  status?: T;
  owner?: T;
  description?: T;
  resolution?: T;
  openedAt?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  eventType?: T;
  kind?: T;
  occurredAt?: T;
  summary?: T;
  details?: T;
  owner?: T;
  opportunity?: T;
  fromStage?: T;
  toStage?: T;
  lossReason?: T;
  relatedTo?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-exports_select".
 */
export interface ReportExportsSelect<T extends boolean = true> {
  status?: T;
  delivery?: T;
  requestedAt?: T;
  startedAt?: T;
  completedAt?: T;
  requestedBy?: T;
  requestedByName?: T;
  requestedByEmail?: T;
  filename?: T;
  semanticVersion?: T;
  snapshotGeneratedAt?: T;
  filters?: T;
  estimatedRows?: T;
  fileSizeBytes?: T;
  file?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  disabledSections?:
    | (
        | 'hero'
        | 'manifesto'
        | 'selectedObjects'
        | 'matter'
        | 'signature'
        | 'matterInterlude'
        | 'provenance'
        | 'privateInvitation'
      )[]
    | null;
  heroMode: 'single' | 'carousel';
  heroSlides?:
    | {
        desktopImage: {
          image: number | Media;
          /**
           * Descreva a imagem para pessoas que usam leitores de tela.
           */
          alt: string;
          caption?: string | null;
        };
        mobileImage: {
          image: number | Media;
          /**
           * Descreva a imagem para pessoas que usam leitores de tela.
           */
          alt: string;
          caption?: string | null;
        };
        statement: string;
        callToAction?: {
          label?: string | null;
          destinationType?: ('internal' | 'external' | 'whatsapp') | null;
          /**
           * Exemplo: /colecao
           */
          path?: string | null;
          url?: string | null;
        };
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  autoplay?: boolean | null;
  autoplaySeconds?: number | null;
  manifestoEyebrow?: string | null;
  manifestoTitle?: string | null;
  manifestoCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  manifestoPrimaryImage?: {
    image?: (number | null) | Media;
    /**
     * Descreva a imagem para pessoas que usam leitores de tela.
     */
    alt?: string | null;
    caption?: string | null;
  };
  manifestoSecondaryImage?: {
    image?: (number | null) | Media;
    /**
     * Descreva a imagem para pessoas que usam leitores de tela.
     */
    alt?: string | null;
    caption?: string | null;
  };
  /**
   * Selecione até 4 produtos. Nenhum dado do produto é copiado aqui.
   */
  selectedProducts?: (number | Product)[] | null;
  matterPanels?:
    | {
        category: number | Category;
        image: {
          image: number | Media;
          /**
           * Descreva a imagem para pessoas que usam leitores de tela.
           */
          alt: string;
          caption?: string | null;
        };
        eyebrow?: string | null;
        headline: string;
        copy?: string | null;
        callToAction?: {
          label?: string | null;
          destinationType?: ('internal' | 'external' | 'whatsapp') | null;
          /**
           * Exemplo: /colecao
           */
          path?: string | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  signatureSlides?:
    | {
        product: number | Product;
        eyebrow?: string | null;
        headline?: string | null;
        copy?: string | null;
        id?: string | null;
      }[]
    | null;
  provenanceTitle?: string | null;
  provenanceCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  provenanceImage?: {
    image?: (number | null) | Media;
    /**
     * Descreva a imagem para pessoas que usam leitores de tela.
     */
    alt?: string | null;
    caption?: string | null;
  };
  provenanceSteps?:
    | {
        title: string;
        copy?: string | null;
        id?: string | null;
      }[]
    | null;
  provenanceCallToAction?: {
    label?: string | null;
    destinationType?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Exemplo: /colecao
     */
    path?: string | null;
    url?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    socialImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  publicationRevision?: string | null;
  publicationContractVersion?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title: string;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: {
    image?: (number | null) | Media;
    /**
     * Descreva a imagem para pessoas que usam leitores de tela.
     */
    alt?: string | null;
    caption?: string | null;
  };
  maisonTitle?: string | null;
  maisonCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  maisonImage?: {
    image?: (number | null) | Media;
    /**
     * Descreva a imagem para pessoas que usam leitores de tela.
     */
    alt?: string | null;
    caption?: string | null;
  };
  visionTitle?: string | null;
  visionCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  visionImage?: {
    image?: (number | null) | Media;
    /**
     * Descreva a imagem para pessoas que usam leitores de tela.
     */
    alt?: string | null;
    caption?: string | null;
  };
  provenanceTitle?: string | null;
  provenanceCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  provenanceImage?: {
    image?: (number | null) | Media;
    /**
     * Descreva a imagem para pessoas que usam leitores de tela.
     */
    alt?: string | null;
    caption?: string | null;
  };
  callToAction?: {
    label?: string | null;
    destinationType?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Exemplo: /colecao
     */
    path?: string | null;
    url?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    socialImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  title: string;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  useOfficialChannels?: boolean | null;
  channels?:
    | {
        label: string;
        kind: 'instagram' | 'email' | 'phone' | 'whatsapp' | 'website' | 'other';
        value: string;
        url?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  serviceHours?: string | null;
  callToAction?: {
    label?: string | null;
    destinationType?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Exemplo: /colecao
     */
    path?: string | null;
    url?: string | null;
  };
  image?: {
    image?: (number | null) | Media;
    /**
     * Descreva a imagem para pessoas que usam leitores de tela.
     */
    alt?: string | null;
    caption?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    socialImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-page".
 */
export interface CollectionPage {
  id: number;
  title: string;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  visibleFilters?: ('category' | 'material' | 'availability' | 'price')[] | null;
  allLabel?: string | null;
  inquiryLabel?: string | null;
  emptyStateTitle: string;
  emptyStateCopy?: string | null;
  emptyStateCallToAction?: {
    label?: string | null;
    destinationType?: ('internal' | 'external' | 'whatsapp') | null;
    /**
     * Exemplo: /colecao
     */
    path?: string | null;
    url?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    socialImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Selecione somente as categorias raiz. Títulos, slugs, filhos e destaques continuam vindo de Categorias.
   */
  roots?:
    | {
        category: number | Category;
        order?: number | null;
        desktopMode?: ('mega' | 'link') | null;
        mobileMode?: ('drilldown' | 'link') | null;
        highlightLimit?: number | null;
        id?: string | null;
      }[]
    | null;
  mainLinks?:
    | {
        label: string;
        path: string;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  categoryLinks?: (number | Category)[] | null;
  utilityLinks?:
    | {
        label: string;
        path: string;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  defaultSeoTitle?: string | null;
  defaultSeoDescription?: string | null;
  officialChannels?:
    | {
        label: string;
        kind: 'instagram' | 'email' | 'phone' | 'whatsapp' | 'website' | 'other';
        value: string;
        url?: string | null;
        active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Exemplo: https://esmera.com.br
   */
  frontendURL?: string | null;
  footerStatement?: string | null;
  locationLabel?: string | null;
  privacyLabel?: string | null;
  privacyHref?: string | null;
  termsLabel?: string | null;
  termsHref?: string | null;
  /**
   * Apenas sinaliza integração real. O CMS não inventa métricas de tráfego.
   */
  analyticsConfigured?: boolean | null;
  /**
   * Regra central de parcelamento. O storefront calcula as parcelas a partir daqui — nunca escreva o parcelamento à mão em cada produto.
   */
  paymentTerms?: {
    maxInstallments?: number | null;
    /**
     * Até quantas parcelas ficam sem juros.
     */
    interestFreeInstallments?: number | null;
    /**
     * Ex.: 5000 = R$ 50,00. 0 desativa o piso.
     */
    minimumInstallmentCents?: number | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Regras reais que alimentam a Payload Jobs Queue. Alterações afetam apenas novos agendamentos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "after-sales-automation".
 */
export interface AfterSalesAutomation {
  id: number;
  preparationEnabled?: boolean | null;
  /**
   * Usado quando a venda não possui entrega prevista. Zero agenda a tarefa imediatamente.
   */
  preparationDelayHours?: number | null;
  satisfactionEnabled?: boolean | null;
  /**
   * Regra padrão D+3.
   */
  satisfactionDelayDays?: number | null;
  testimonialEnabled?: boolean | null;
  /**
   * Regra padrão D+15.
   */
  testimonialDelayDays?: number | null;
  maintenanceEnabled?: boolean | null;
  /**
   * Regra padrão D+90.
   */
  maintenanceDelayDays?: number | null;
  maintenanceScope: 'selected' | 'all';
  maintenanceProducts?: (number | Product)[] | null;
  maintenanceCategories?: (number | Category)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  disabledSections?: T;
  heroMode?: T;
  heroSlides?:
    | T
    | {
        desktopImage?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
            };
        mobileImage?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
            };
        statement?: T;
        callToAction?:
          | T
          | {
              label?: T;
              destinationType?: T;
              path?: T;
              url?: T;
            };
        active?: T;
        id?: T;
      };
  autoplay?: T;
  autoplaySeconds?: T;
  manifestoEyebrow?: T;
  manifestoTitle?: T;
  manifestoCopy?: T;
  manifestoPrimaryImage?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
      };
  manifestoSecondaryImage?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
      };
  selectedProducts?: T;
  matterPanels?:
    | T
    | {
        category?: T;
        image?:
          | T
          | {
              image?: T;
              alt?: T;
              caption?: T;
            };
        eyebrow?: T;
        headline?: T;
        copy?: T;
        callToAction?:
          | T
          | {
              label?: T;
              destinationType?: T;
              path?: T;
              url?: T;
            };
        id?: T;
      };
  signatureSlides?:
    | T
    | {
        product?: T;
        eyebrow?: T;
        headline?: T;
        copy?: T;
        id?: T;
      };
  provenanceTitle?: T;
  provenanceCopy?: T;
  provenanceImage?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
      };
  provenanceSteps?:
    | T
    | {
        title?: T;
        copy?: T;
        id?: T;
      };
  provenanceCallToAction?:
    | T
    | {
        label?: T;
        destinationType?: T;
        path?: T;
        url?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  publicationRevision?: T;
  publicationContractVersion?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  heroImage?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
      };
  maisonTitle?: T;
  maisonCopy?: T;
  maisonImage?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
      };
  visionTitle?: T;
  visionCopy?: T;
  visionImage?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
      };
  provenanceTitle?: T;
  provenanceCopy?: T;
  provenanceImage?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
      };
  callToAction?:
    | T
    | {
        label?: T;
        destinationType?: T;
        path?: T;
        url?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  useOfficialChannels?: T;
  channels?:
    | T
    | {
        label?: T;
        kind?: T;
        value?: T;
        url?: T;
        active?: T;
        id?: T;
      };
  serviceHours?: T;
  callToAction?:
    | T
    | {
        label?: T;
        destinationType?: T;
        path?: T;
        url?: T;
      };
  image?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collection-page_select".
 */
export interface CollectionPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  visibleFilters?: T;
  allLabel?: T;
  inquiryLabel?: T;
  emptyStateTitle?: T;
  emptyStateCopy?: T;
  emptyStateCallToAction?:
    | T
    | {
        label?: T;
        destinationType?: T;
        path?: T;
        url?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        socialImage?: T;
        noIndex?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  roots?:
    | T
    | {
        category?: T;
        order?: T;
        desktopMode?: T;
        mobileMode?: T;
        highlightLimit?: T;
        id?: T;
      };
  mainLinks?:
    | T
    | {
        label?: T;
        path?: T;
        active?: T;
        id?: T;
      };
  categoryLinks?: T;
  utilityLinks?:
    | T
    | {
        label?: T;
        path?: T;
        active?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  officialChannels?:
    | T
    | {
        label?: T;
        kind?: T;
        value?: T;
        url?: T;
        active?: T;
        id?: T;
      };
  frontendURL?: T;
  footerStatement?: T;
  locationLabel?: T;
  privacyLabel?: T;
  privacyHref?: T;
  termsLabel?: T;
  termsHref?: T;
  analyticsConfigured?: T;
  paymentTerms?:
    | T
    | {
        maxInstallments?: T;
        interestFreeInstallments?: T;
        minimumInstallmentCents?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "after-sales-automation_select".
 */
export interface AfterSalesAutomationSelect<T extends boolean = true> {
  preparationEnabled?: T;
  preparationDelayHours?: T;
  satisfactionEnabled?: T;
  satisfactionDelayDays?: T;
  testimonialEnabled?: T;
  testimonialDelayDays?: T;
  maintenanceEnabled?: T;
  maintenanceDelayDays?: T;
  maintenanceScope?: T;
  maintenanceProducts?: T;
  maintenanceCategories?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateAfterSalesTask".
 */
export interface TaskCreateAfterSalesTask {
  input: {
    automationKey: string;
    saleId: string;
    title: string;
    type: 'delivery_confirmation' | 'satisfaction' | 'testimonial' | 'maintenance' | 'curation' | 'custom';
    dueAt: string;
    priority: 'low' | 'normal' | 'high' | 'urgent';
    assigneeId?: string | null;
    notes?: string | null;
  };
  output: {
    taskID?: string | null;
    created: boolean;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSyncActiveShipments".
 */
export interface TaskSyncActiveShipments {
  input?: unknown;
  output: {
    configured: boolean;
    scanned: number;
    updated: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateReportExport".
 */
export interface TaskGenerateReportExport {
  input: {
    exportId: string;
  };
  output: {
    exportId: string;
    fileId: string;
    filename: string;
    semanticVersion: string;
    fileSizeBytes: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskProductImport".
 */
export interface TaskProductImport {
  input: {
    importId: string;
  };
  output: {
    importId: string;
    status: string;
    created: number;
    updated: number;
    skipped: number;
    errored: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}